function [ fail, pszCamFile ] = OptotrakLoadCameraParameters( pszCamFile )
%OPTOTRAKLOADCAMERAPARAMETERS
% [ fail, pszCamFile ] = OptotrakLoadCameraParameters( pszCamFile )
% Loads camera settings from the given file
%This is the function that handles .cam files generated by TransputerDetermineCfg()
%   fail is the return value of the function. The API docs don't go into details on what this does.
%   So, 0 for all good, and pretty much anything else for fail.

    % Prepare pointer inputs
    szCamFile_pointer = libpointer('cstring', pszCamFile);

    if(isunix)
        fail = calllib('liboapi', 'OptotrakLoadCameraParameters', szCamFile_pointer);
    else
        if(new_or_old)
            fail = calllib('oapi64', 'OptotrakLoadCameraParameters', szCamFile_pointer);
        else
            fail = calllib('oapi', 'OptotrakLoadCameraParameters', szCamFile_pointer);
        end
    end

    % Get updated data with the pointer
    pszCamFile = get(szCamFile_pointer, 'Value');

    % Clean up pointers so Matlab won't crash on repeated use of this function
    clear szCamFile_pointer;

end
